// Server Actions
export const SET_USERS_FROM_SERVER = 'SET_USERS_FROM_SERVER';
export const ADD_MESSAGE_FROM_SERVER = 'ADD_MESSAGE_FROM_SERVER';
export const TYPING_MESSAGE_FROM_SERVER = 'TYPING_MESSAGE_FROM_SERVER';
export const STOP_TYPING_MESSAGE_FROM_SERVER = 'STOP_TYPING_MESSAGE_FROM_SERVER';

// Client Actions
export const ADD_MESSAGE_FROM_CLIENT = 'ADD_MESSAGE_FROM_CLIENT';
export const TYPING_MESSAGE_FROM_CLIENT = 'TYPING_MESSAGE_FROM_CLIENT';
export const STOP_TYPING_MESSAGE_FROM_CLIENT = 'STOP_TYPING_MESSAGE_FROM_CLIENT';
